from .weather import *
from .nasa import *
from .jokes import *
from .converter import *
from .stats import *
from .newsletter import *
from .cinema import *
from .bd import *
from .trivia import *
from .translator import *
from .leisure import *